USE [AxDB]
GO

DECLARE @JournalNum AS VARCHAR(100)='00639'
DECLARE @UserId AS VARCHAR(100)='Admin'
DECLARE @DataAreaId AS VARCHAR(100)='usmf'
DECLARE @Voucher AS VARCHAR(100)='GNJL000814'

SELECT * FROM [dbo].[LEDGERJOURNALTRANS]
WHERE [dbo].[LEDGERJOURNALTRANS].DATAAREAID = @DataAreaId
AND [dbo].[LEDGERJOURNALTRANS].JOURNALNUM = @JournalNum

SELECT * FROM [dbo].[BUDGETSOURCE]
WHERE [dbo].[BUDGETSOURCE].LEDGERENTRYJOURNALNUMBER = @JournalNum

SELECT * FROM [dbo].[TRANSACTIONLOG]
WHERE [dbo].[TRANSACTIONLOG].TXT LIKE @JournalNum + '%'
AND [dbo].[TRANSACTIONLOG].DATAAREAID = @DataAreaId

SELECT * FROM [dbo].[GENERALJOURNALENTRY]
WHERE [dbo].[GENERALJOURNALENTRY].SUBLEDGERVOUCHER = @Voucher
AND [dbo].[GENERALJOURNALENTRY].CREATEDBY = @UserId

SELECT * FROM [dbo].[LEDGERENTRYJOURNAL]
WHERE [dbo].[LEDGERENTRYJOURNAL].JOURNALNUMBER = @JournalNum
AND [dbo].[LEDGERENTRYJOURNAL].RECID = 68719512388 -- Ledger Entry Journal Id from GENERALJOURNALENTRY

SELECT * FROM [dbo].[SUBLEDGERVOUCHERGENERALJOURNALENTRY]
WHERE [dbo].[SUBLEDGERVOUCHERGENERALJOURNALENTRY].VOUCHER = @Voucher

SELECT * FROM [dbo].[GENERALJOURNALACCOUNTENTRY]
WHERE [dbo].[GENERALJOURNALACCOUNTENTRY].GENERALJOURNALENTRY = 68719623594

SELECT * FROM [dbo].[DIMENSIONFOCUSUNPROCESSEDTRANSACTIONS]
WHERE [dbo].[DIMENSIONFOCUSUNPROCESSEDTRANSACTIONS].GENERALJOURNALENTRY = 68719623594

SELECT * FROM [dbo].[LEDGERJOURNALTABLE]
WHERE [dbo].[LEDGERJOURNALTABLE].JOURNALNUM = @JournalNum
AND [dbo].[LEDGERJOURNALTABLE].DATAAREAID = @DataAreaId